### ISSUE TITLE
Issues trying to install AmpLocker

### ISSUE THREAD

**Issue by minikN** [polygon/audio.nix#1]
Hello,

Thanks very much for the packaging of AmpLocker. However, after [adding](https://github.com/minikN/nix/commit/244be3788cf84d0acd77365bb742426a4acfa162) your repo to my flake as an input, I can't install `AmpLocker`:

```console
nix > sudo nixos-rebuild switch --flake .#                                                                  [1]
building the system configuration...
trace: warning: `overrideScope'` (from `lib.makeScope`) has been renamed to `overrideScope`.
trace: warning: `overrideScope'` (from `lib.makeScope`) has been renamed to `overrideScope`.
trace: warning: `overrideScope'` (from `lib.makeScope`) has been renamed to `overrideScope`.
error: builder for '/nix/store/5myp7nww4jy5lwg7sz1i3lggcjdlym08-Amp+Locker+Linux.zip.drv' failed with exit code 
1;
 last 10 log lines:
 >
 > ***
 > This Nix expression requires the Amp Locker plugin download is
 > already part of the store. Please download your purchased
 > copy and place the Amp+Locker+Linux.zip file into the Nix Store with:
 >
 > "nix store add-file Amp+Locker+Linux.zip"
 >
 > ***
 >
 For full logs, run 'nix log /nix/store/5myp7nww4jy5lwg7sz1i3lggcjdlym08-Amp+Locker+Linux.zip.drv'.
```

Of course, I added the file, actually I tried different ways:
```console
Downloads > nix-store --add-fixed sha256 Amp+Locker+Linux.zip
/nix/store/ppp24zlwyy45aqxdis0n4r0fb28gsfqr-Amp+Locker+Linux.zip
Downloads > nix store add-file Amp+Locker+Linux.zip
/nix/store/ppp24zlwyy45aqxdis0n4r0fb28gsfqr-Amp+Locker+Linux.zip
```

However, the error remains the same. I'd appreciate any help on this.

On a side note, I tried packaging [AmpLocker](https://github.com/minikN/nix/blob/master/packages/audio/amp-locker.nix) and the [Blacksun](https://github.com/minikN/nix/blob/master/packages/audio/audioassault-blacksun.nix) plugin myself, with limited success.

After looking at your derivation for AmpLocker, I think I need to patch `so` file in the same way you did to replace the references to `/opt/Audio Assault`. Could you explain to me how you created `vst3.patch`? I guess I could just take what you did, but the Blacksun plugin is only available as vst2, so I'd like to understand the process and do it myself for the plugin (if possible).

Thanks again, I appreciate it!

**Comment by polygon** [comment]
Maybe they released a new version and hence, the files are different. Or possibly, they customize each download and checksums will never match. You're the first person to try this as far as I am concerned. I'll try downloading this again and update the package when I find the time.

For the patching, I used Ghidra. I looked through the string table for a string containing `/opt/Audio Assault` and then for references to this string. You will only find one place where this is referenced. I then looked through the string table again to find something long enough that it could fit a typical path to the Nix store and found it in the description of a random amp or pedal. So the binary patch modifies the reference to `/opt/Audio Assault` to point to this new amplifier description string. I then use `dd` to replace the description string at build time with the nix store path.

**Comment by minikN** [comment]
Hello,

I'll close this issue for now.Just FYI: I contacted Audio Assault on this matter and asked them if it is possible to remove the hardcoding of `/opt/Audio Assault` from their applications and actually give the user the option to set the path (either through an env var or runtime param).

They were open about it and forwarded my request to the developers, but told me it could take a couple of months before they find time to implement it. But it's something!
